### ISSUE TITLE
Error Writing Request Body

### ISSUE THREAD

**Issue by mtgnoah** [ClickHouse/spark-clickhouse-connector#204]
One or two tasks will fail out of many when writing a heavily partitioned table that uses a UDF to clickhouse and I can't figure out what is causing it
```
xenon.clickhouse.exception.CHServerException: [HTTP]default@192.168.0.202:8123}/default [1002] Error writing request body to server, server ClickHouseNode [uri=http://192.168.0.202:8123/default]@1139606723
	at xenon.clickhouse.client.NodeClient.syncInsert(NodeClient.scala:126)
	at xenon.clickhouse.client.NodeClient.syncInsertOutputJSONEachRow(NodeClient.scala:85)
	at xenon.clickhouse.write.ClickHouseWriter.$anonfun$doFlush$1(ClickHouseWriter.scala:231)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at xenon.clickhouse.Utils$.retry(Utils.scala:87)
	at xenon.clickhouse.write.ClickHouseWriter.doFlush(ClickHouseWriter.scala:229)
	at xenon.clickhouse.write.ClickHouseWriter.flush(ClickHouseWriter.scala:217)
	at xenon.clickhouse.write.ClickHouseWriter.commit(ClickHouseWriter.scala:262)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$1(WriteToDataSourceV2Exec.scala:453)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1538)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:480)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:381)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by pan3793** [comment]
1002 is unknown exception.
```
UNKNOWN_EXCEPTION(1002, "UNKNOWN_EXCEPTION");
```

Lower the batch size may helps.

https://housepower.github.io/spark-clickhouse-connector/configurations/

**Comment by mzitnik** [comment]
@mtgnoah did it helped you?

**Comment by BentsiLeviav** [comment]
closing it as we couldn't get @mtgnoah's reply for almost a year.
@mtgnoah - feel free to reopen if needed.

**Comment by BentsiLeviav** [comment]
Hi @SwatGetmann 

From what I see @mtgnoah had a `1002` error which is an `unknown exception`.
What causes you to think you have the same issue?

The error you are getting looks like this open issue https://github.com/ClickHouse/spark-clickhouse-connector/issues/365

If that is indeed the case, let's continue the discussion there. In addition **please share the following information so we can reproduce the issue**:
* DDL to run on ClickHouse
* Code example to reproduce the issue.
* What scale do you handle? Columns/number of rows/data size
* Can you tell us about your Spark setup? how many parallel insets do you do against CH? (how many partitions), how many resources do you use?

**Comment by SwatGetmann** [comment]
> What causes you to think you have the same issue?

TBH, I think that both issues, this and https://github.com/ClickHouse/spark-clickhouse-connector/issues/365 have the same commonality, becasue I also had encountered 1002 along the way.
 also look at the stacktraces - they are close to each other logically, as the hierarchy of function calls is the same - it is the main point of reference for me after a week full of trials to find any info on the matter:
```
# initial comment by @mtgnoah 
at xenon.clickhouse.client.NodeClient.syncInsert(NodeClient.scala:126)
	at xenon.clickhouse.client.NodeClient.syncInsertOutputJSONEachRow(NodeClient.scala:85)
	at xenon.clickhouse.write.ClickHouseWriter.$anonfun$doFlush$1(ClickHouseWriter.scala:231)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
...

# my comment
        at com.clickhouse.spark.client.NodeClient.syncInsert(NodeClient.scala:150)
        at com.clickhouse.spark.client.NodeClient.syncInsertOutputJSONEachRow(NodeClient.scala:115)
        at com.clickhouse.spark.write.ClickHouseWriter.$anonfun$doFlush$1(ClickHouseWriter.scala:256)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
...

# 365 issue comment
	at com.clickhouse.spark.client.NodeClient.syncInsert(NodeClient.scala:146)
	at com.clickhouse.spark.client.NodeClient.syncInsertOutputJSONEachRow(NodeClient.scala:111)
	at com.clickhouse.spark.write.ClickHouseWriter.$anonfun$doFlush$1(ClickHouseWriter.scala:228)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
```

as you see in provided trace excerpts, they all have **same hierarchies**.
Also, I don't know if that had been noted anywhere recenly regarding the issue, there are 0 error logs on CH cluster nodes. So that makes me wonder what is really happening, is it even an issue? Because insets do work, it's just a `connection reset by peer` / `broken pipe` / `unknown exception` kinds of error I keep getting.

And answering your questions:
> DDL to run on ClickHouse

It was a spark insert of DF (at least 10k rows) into CH table. It's done like this within pyspark
```
# settings.clickhouse_output_num_partitions = 10
   (
            batch
            .coalesce(settings.clickhouse_output_num_partitions)
            .writeTo(f'clickhouse.{settings.clickhouse_database}.{settings.clickhouse_table}')
            .append()
        )
```

> Code example to reproduce the issue.

I cannot share it so easily as it's a production code, NDAs and stuff. But in short, it's a simple app that reads from Kafka, explodes msgs a bit + performs some logic, and writes them down into CH. 
I'll try to provide smth of a simplified pyspark main.py that can be run to face the issue, but later.

> Can you tell us about your Spark setup? how many parallel insets do you do against CH? (how many partitions), how many resources do you use?

There are known to be at least 110 unique partitions in total, partition key is not based on datetime but on some integer field with low cardinality + salt for one skewed partition.
Also, note that locally (10k input batches + 5k output batch sizes, single driver w ~1gb mem, no execs) there is no such error, but on infrastructure (k8s, 10i1c execs 1.5gb each core, 1i2c driver 6gb core) it fails.
As I get it, parallel inserts are limited only by the Spark number of cores, which is (10 instances x 1 core) = 10.

> What scale do you handle?  Columns/number of rows/data size

I ought to process incoming data fast enough, near real-time. The volume range might be dynamic, but we have a max input rate = 500k messages, which may be exploded up to 4-5 MLN rows in the initial DF that should be offloaded as fast as a possible. But realistically, we offload it, f.e. during Reading Lag compensation, within ~30s time mark.

**Comment by scottme** [comment]
> I guess I have made a breakthrough - tweaking of the parameter `max_query_size` (I've set it equal to 67108864 = 64mb) helped to increase output ch write batch size form 500-800 for my dataset to 1.5k, 3k and even 10k, and eventually mitigated / resolved the issue for me.

can you point where is this parameter, how it could resolve the issue? thanks.

**Comment by SwatGetmann** [comment]
> > I guess I have made a breakthrough - tweaking of the parameter `max_query_size` (I've set it equal to 67108864 = 64mb) helped to increase output ch write batch size form 500-800 for my dataset to 1.5k, 3k and even 10k, and eventually mitigated / resolved the issue for me.
> 
> can you point where is this parameter, how it could resolve the issue? thanks. [@SwatGetmann](https://github.com/SwatGetmann)

@scottme , here it is, in the CH docs: https://clickhouse.com/docs/operations/settings/settings#max_query_size
