### ISSUE TITLE
NodeClient initialization fails intermittently when attempting to pull get scala version

### ISSUE THREAD

**Issue by mikech-goodcover** [ClickHouse/spark-clickhouse-connector#358]
### Describe the bug

NodeClient initialization intermittently fails when trying to pull package metadata.

Seems to be attempting to grab the scala version from the package version, and getting it in an unexpected format.

Introduced here:
https://github.com/ClickHouse/spark-clickhouse-connector/commit/6dd82f18f77166af50c79faa0c83f90255817922

### Expected behaviour

Doesn't blow up. 

### Error log

```
2024-09-06T06:47:24.942658739Z java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
2024-09-06T06:47:24.942665879Z 	at com.clickhouse.spark.client.NodeClient.userAgent$lzycompute(NodeClient.scala:51)
2024-09-06T06:47:24.942667819Z 	at com.clickhouse.spark.client.NodeClient.userAgent(NodeClient.scala:45)
2024-09-06T06:47:24.942671599Z 	at com.clickhouse.spark.client.NodeClient.<init>(NodeClient.scala:70)
2024-09-06T06:47:24.942675009Z 	at com.clickhouse.spark.client.NodeClient$.apply(NodeClient.scala:38)
2024-09-06T06:47:24.942681709Z 	at com.clickhouse.spark.ClickHouseCatalog.initialize(ClickHouseCatalog.scala:77)
...
```

#### Environment
* Apache Spark version: 3.5
* Scala version: 2.13
* Connection version: 0.8.0

#### ClickHouse server
* ClickHouse Server version: 0.2.5

**Comment by mzitnik** [comment]
Hi @mikech-goodcover 
Thanks for the feedback looking into it

**Comment by mzitnik** [comment]
I was testing with our example code works fine

**Comment by dispalt** [comment]
So I am guessing this has something to do with shading.  It would be nice if we could wrap the whole thing in a try/catch and fall back to using the generic string

**Comment by mzitnik** [comment]
I planned to do this, but I would like to reproduce it. 
Can you describe how you are running it?
